package edu.ucsd.cse110.habitizer.lib.domain;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;
//Autogenerated using ChatGPT
public class RoutineTest {
    private Routine routine;

    @Before
    public void setUp() {
        routine = new Routine(1, "Morning Routine", 0, 30);
    }

    @Test
    public void testInitialization() {
        assertEquals("Morning Routine", routine.name());
        assertEquals(1, (int) routine.id());
        assertEquals(0, routine.sortOrder());
        assertEquals(30, routine.getGoalTime());
        assertFalse(routine.isStarted());
        assertFalse(routine.isCompleted());
    }

    @Test
    public void testStart() {
        routine.start();
        assertTrue(routine.isStarted());
    }

    @Test
    public void testComplete() {
        routine.complete();
        assertTrue(routine.isCompleted());
    }

    @Test
    public void testReset() {
        routine.start();
        routine.complete();
        routine.reset();
        assertFalse(routine.isStarted());
        assertFalse(routine.isCompleted());
    }

    @Test
    public void testSetGoalTime() {
        routine.setGoalTime(45);
        assertEquals(45, routine.getGoalTime());
    }

    @Test
    public void testWithSortOrder() {
        routine.withSortOrder(2);
        assertEquals(2, routine.sortOrder());
    }

    @Test
    public void testWithId() {
        routine.withId(10);
        assertEquals(10, (int) routine.id());
    }

    @Test
    public void testRename() {
        routine.rename("Evening Routine");
        assertEquals("Evening Routine", routine.name());
    }

    @Test
    public void testRoutineBuilder() {
        Routine builtRoutine = Routine.builder()
                .setId(2)
                .setName("Workout Routine")
                .setSortOrder(1)
                .setGoalTime(60)
                .build();

        assertEquals("Workout Routine", builtRoutine.name());
        assertEquals(2, (int) builtRoutine.id());
        assertEquals(1, builtRoutine.sortOrder());
        assertEquals(60, builtRoutine.getGoalTime());
    }
}
